### ISSUE TITLE
Работа RGB силовых блоков sd-1-180

### ISSUE THREAD

**Issue by tenens-fusum** [SergejPr/HomeAssistance-NooLite#14]
Добрый день.
В первую очередь, спасибо вам за вашу разработку. Сказать что она полезная - не сказать ничего.
Столкнулся с ошибками при добавлении RGB модулей на основе силовых блоков sd-1-180 через USB стик.
Иногда работает включение/выключение (Включается белый цвет). Но как правило выдает ошибки вида "unsupported operand type(s) for /: 'NoneType' and 'int'" как при операци вкл/выкл, так и при смене цвета или изменении яркости.
Пробовал править кастомизацию и занимался прочим шаманизмом, но уже не знаю куда можно копать.
Noolite-F силовые блоки работают отлично. Привязывал блоки к стику через Noolite One (командой bind).

Настройки RGB
`#RGB подсветка
- platform: noolite
  channel: 10
  type: rgb_led
  name: "bath_RGB"
  scan_interval: 57
  mode: noolite`

Версия HA
## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4985
Installed Version | 1.15.2
Stage | running
Available Repositories | 877
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.6
docker_version | 20.10.7
disk_total | 116.7 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.4.0), Samba share (9.5.1), Check Home Assistant configuration (3.9.0), Network UPS Tools (0.8.0), Visual Studio Code (3.6.2), Terminal & SSH (9.2.1), Let's Encrypt (4.11.0), NGINX Home Assistant SSL proxy (3.0.2), Nginx Proxy Manager (0.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

### Лог ошибки при попытке смены цвета.

> Logger: homeassistant.components.websocket_api.http.connection
> Source: custom_components/noolite/light.py:110
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 10:22:49 (2 occurrences)
> Last logged: 10:22:52
> 
> [547973303696] unsupported operand type(s) for /: 'NoneType' and 'int'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
>     await handler.job.target(service_call)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
>     await self.hass.helpers.service.entity_service_call(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
>     await result
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in async_handle_light_on_service
>     await light.async_turn_on(**filter_turn_on_params(light, params))
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
>     await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/noolite/light.py", line 110, in turn_on
>     brightness_multiplier = self._brightness / 255
> TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### Изменение яркости
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/noolite/light.py:111
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:37:44 (1 occurrences)
Last logged: 10:37:44

[547973303696] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/noolite/light.py", line 111, in turn_on
    red = (self._rgb[0] * brightness_multiplier) / 255
TypeError: 'NoneType' object is not subscriptable
`

### Включение/выключение
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/noolite/light.py:111
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:37:44 (3 occurrences)
Last logged: 10:38:31

[547973303696] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/noolite/light.py", line 111, in turn_on
    red = (self._rgb[0] * brightness_multiplier) / 255
TypeError: 'NoneType' object is not subscriptable`

**Comment by SergejPr** [comment]
Добрый день, постараюсь посмотреть в чем может быть проблема в ближайшее время.

**Comment by SergejPr** [comment]
Исправил в версии 0.1.3. Теперь RGB модуль работает как надо.
